services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betalentech_app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - gateway-mock

  mysql:
    image: mysql:8
    container_name: betalentech_mysql
    restart: always
    environment:
      MYSQL_DATABASE: betalentech
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  gateway-mock:
    image: matheusprotzen/gateways-mock
    container_name: gateway_mock
    ports:
      - "3001:3001"
      - "3002:3002"

volumes:
  mysql_data:
